### ISSUE TITLE
Game crashes whenever try to play

### ISSUE THREAD

**Issue by ICanPlayAndMakeGames** [MianReplicate/Lifesteal#12]
**Versions**
Minecraft Version: 1.20.4
Forge Version: Not got forge
Mod Version: 1.20.4

**Describe the bug**
Anytime I run it on client or on server I get this error and it crashes

java.lang.IllegalAccessError: class fabric.net.goose.lifesteal.data.HealthData tried to access private field net.minecraft.class_1322.field_46248 (fabric.net.goose.lifesteal.data.HealthData and net.minecraft.class_1322 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57d5872c)
	at fabric.net.goose.lifesteal.data.HealthData.getHeartModifiedTotal(HealthData.java:191)
	at fabric.net.goose.lifesteal.data.HealthData.getHPDifferenceRequiredForBan(HealthData.java:211)
	at net.minecraft.class_1657.md47fb60$lifesteal$lambda$tickMethod$0$2(class_1657.java:2368)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1657.handler$zne000$lifesteal$tickMethod(class_1657.java:2366)
	at net.minecraft.class_1657.method_5773(class_1657.java)
	at net.minecraft.class_3222.method_14226(class_3222.java:519)
	at net.minecraft.class_3244.method_18784(class_3244.java:257)
	at net.minecraft.class_2535.method_10754(class_2535.java:379)
	at net.minecraft.class_3242.method_14357(class_3242.java:176)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:959)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**To Reproduce**

Just play it on fabric 1.20.4

**Expected behavior**
It crashes

**Screenshots**
![image](https://github.com/LoxiGoose/Lifesteal/assets/119879085/dfda3bd7-63ae-49a1-9a26-5cbfd2414e11)
![image](https://github.com/LoxiGoose/Lifesteal/assets/119879085/a81cd97e-c4a2-4079-a9d9-9a0b40857063)

**Additional context**
None

**Comment by MianReplicate** [comment]
I am aware of this bug. I'll fix it when I can but for now it'll have to wait since I am busy with life.

**Comment by MianReplicate** [comment]
Fixed in the new 8.0.1 update. Sorry if there were any inconveniences.
