### ISSUE TITLE
[BUG] Crash on player kill

### ISSUE THREAD

**Issue by sammy-ette** [MianReplicate/Lifesteal#24]
**Versions**
Minecraft Version: 1.20.1
Loader Version: 0.16.5
Mod Version: 7.1.1
*If you are using Fabric, please also specify the Fabric API version*
0.92.1

**Describe the bug**
Dedicated server crashed after a player killed another player. I'm not sure the exact cause beside that, but I have a big mod pack running with optimization mods like Servercore. (would that be an issue)
Here's a link to my packwiz modpack: https://github.com/Lunarienya/X-Zenless/tree/main/mods

```
Oct 09 01:53:58 lunarie start.sh[69402]: net.minecraft.class_148: Ticking entity
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at java.lang.Thread.run(Thread.java:833) ~[?:?]
Oct 09 01:53:58 lunarie start.sh[69402]: Caused by: java.util.ConcurrentModificationException
Oct 09 01:53:58 lunarie start.sh[69402]:         at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at mc.mian.lifesteal.data.LSData.refreshHealth(LSData.java:294) ~[lifesteal-7.1.1+1.20.1.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at mc.mian.lifesteal.util.LSUtil.lambda$gainHealth$4(LSUtil.java:289) ~[lifesteal-7.1.1+1.20.1.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at mc.mian.lifesteal.util.LSUtil.gainHealth(LSUtil.java:285) ~[lifesteal-7.1.1+1.20.1.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1657.increaseHealth(class_1657.java:2412) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1657.md176590$lifesteal$lambda$onDeath$2$0(class_1657.java:2475) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1657.handler$dld001$lifesteal$onDeath(class_1657.java:2444) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1657.method_16078(class_1657.java) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1309.method_16080(class_1309.java:1413) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_3222.method_6078(class_3222.java:643) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1309.method_5643(class_1309.java:1222) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1657.method_5643(class_1657.java:928) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_3222.method_5643(class_3222.java:732) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1665.method_7454(class_1665.java:374) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1676.method_7488(class_1676.java:153) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1665.method_5773(class_1665.java:227) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1667.method_5773(class_1667.java:104) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
Oct 09 01:53:58 lunarie start.sh[69402]:         ... 5 more
Oct 09 01:53:58 lunarie start.sh[69402]: [01:53:58] [Server thread/ERROR]: This crash report has been saved to: /root/Server/./crash-reports/crash-2024-10-09_01.53.58-server.txt
```

**Comment by sammy-ette** [comment]
it seems to be due to servercore indeed, nevermind

**Comment by MianReplicate** [comment]
Just saw this and I wanted to mention that if you want to use ServerCore, I can look into finding a way to solve the crash.

**Comment by sammy-ette** [comment]
Since it happened again, here's a full crash report: https://safe.saya.moe/oTp4gHEmYg8n.txt

**Comment by MianReplicate** [comment]
I've tried recreating this and it just does not happen. You're going to need to provide a video of the crash happening with a modpack download so I can reproduce the issue.
